name: Akamai SIEM Connector Pipeline

on:
  push:
    tags: [ "*" ]
    paths-ignore:
      - "iac/*.tf"
      - "iac/*.sh"
      - "deploy.sh"
      - "undeploy.sh"
      - "setup.sh"
      - "banner.txt"
      - "about.txt"
      - "*.md"
      - "LICENSE"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Download the project files.
        uses: actions/checkout@v3

      - name: Setting up environment.
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Build services.
        run: ./build.sh

      - name: Package services.
        run: ./package.sh

      - name: Publish services.
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh
